services:
	postgres:
		# IMPORTANT: Using 15-alpine to match existing data directory initialized with PostgreSQL 15.
		# To upgrade to 17, DO NOT just change this tag while reusing the same volume.
		# Follow docs/POSTGRES_UPGRADE.md for a safe dump & restore or pg_upgrade workflow.
		image: postgres:15-alpine
		container_name: axum_postgres
		restart: unless-stopped
		environment:
			POSTGRES_USER: ${POSTGRES_USER:-appuser}
			POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_pass}
			POSTGRES_DB: ${POSTGRES_DB:-app_db}
		volumes:
			# Match dev volume naming (versioned). If you intend to reuse existing data from the old name,
			# do a dump & restore or switch this back temporarily.
			- postgres_data_v15:/var/lib/postgresql/data
		# No host port published in prod to avoid conflicts with any host-level Postgres
		expose:
			- "5432"
		networks:
			- axum_net

	app:
		environment:
			# In containers, refer to Postgres by its service name and internal port
			DATABASE_URL: postgresql://${POSTGRES_USER:-appuser}:${POSTGRES_PASSWORD:-app_pass}@postgres:5432/${POSTGRES_DB:-app_db}

volumes:
	postgres_data_v15:
		driver: local

networks:
	axum_net:
		driver: bridge
		# See dev compose for external network option instructions.
